module GameOver where

    import Data.IORef
    import Graphics.Rendering.OpenGL hiding (($=))
    import Graphics.UI.GLUT

    type Vertice = (GLfloat, GLfloat)
    type Cor = (GLfloat, GLfloat, GLfloat)

    game :: IO ()
    game = do
        clear [ColorBuffer]
        renderPrimitive Quads $ do
            desenhaMapa ((-1)::GLfloat, 1::GLfloat) ((-0.9)::GLfloat, 1::GLfloat) ((-0.9)::GLfloat, 0.9::GLfloat) ((-1)::GLfloat, 0.9::GLfloat) gameOver
        flush

    -- Desenha uma linha do mapa
    linha :: Vertice -> Vertice -> Vertice -> Vertice -> [Cor] -> IO ()
    linha v1 v2 v3 v4 [cor] = desenhaQuadrado cor v1 v2 v3 v4
    linha v1 v2 v3 v4 (cor:ls) = do 
        desenhaQuadrado cor v1 v2 v3 v4
        linha (mais v1 0.05) (mais v2 0.05) (mais v3 0.05) (mais v4 0.05) ls
            where mais = (\(vx,vy) x -> (vx + x, vy))

    -- Chama a função para desenhar cada linha do mapa
    desenhaMapa :: Vertice -> Vertice -> Vertice -> Vertice -> [[Cor]] -> IO ()
    desenhaMapa v1 v2 v3 v4 [cor] = linha v1 v2 v3 v4 cor
    desenhaMapa v1 v2 v3 v4 (cor:ls) = do 
        linha v1 v2 v3 v4 cor
        desenhaMapa (menos v1 0.1) (menos v2 0.1) (menos v3 0.1) (menos v4 0.1) ls
            where menos = (\(vx,vy) y -> (vx, vy - y))

    -- Utilizado para chamar color3f em vez de chamar color $ Color3 r g b
    color3f :: Cor -> IO ()
    color3f (r, g, b) = color $ Color3 r g (b :: GLfloat)
    
    -- Utilizado para chamar vertex2f em vez de chamar vertex $ Vertex2 x y
    vertex2f :: Vertice -> IO ()
    vertex2f (x, y) = vertex $ Vertex2 x y

    -- Desenha apenas um quadrado
    desenhaQuadrado :: Cor -> Vertice -> Vertice -> Vertice -> Vertice -> IO ()
    desenhaQuadrado cor v1 v2 v3 v4 = do
            color3f cor
            vertex2f v1
            vertex2f v2
            vertex2f v3
            vertex2f v4

{--
                                        
                                        
     ######     ###    ##     ## ######                 
    ##    ##   #####   ###   ### ######                 
    ##        ##   ##  ## # # ## ##                  
    ##   ### ######### ##  #  ## ####  
    ##    ## ##     ## ##     ## ##      
    ##    ## ##     ## ##     ## ######                 
     ######  ##     ## ##     ## ######                        
                                        
      ######  ##    ## ###### #######                              
     ##    ## ##    ## ###### ##    ##
     ##    ## ##    ## ##     ##    ##                          
     ##    ## ##    ## ####   ######
     ##    ##  ##  ##  ##     ##  ##                             
     ##    ##   ####   ###### ##   ##                           
      ######     ##    ###### ##    ##                         
                                        
                                        
                                                                           
--}
    gameOver = [linhaBranca, linhaBranca,
        linha1, linha2, linha3, linha4, linha5, linha6, linha7, linhaBranca,
        linha8, linha9, linha10, linha11, linha12, linha13, linha14,
        linhaBranca,linhaBranca,linhaBranca]

    linhaBranca = [
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat),
            (1::GLfloat,1::GLfloat,1::GLfloat)]

    linha1 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]

    linha2 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
  
    linha3 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha4 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha5 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha6 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha7 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha8 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha9 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha10 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha11 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha12 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha13 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]
    linha14 = [
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (0::GLfloat,0::GLfloat,0::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat),
        (1::GLfloat,1::GLfloat,1::GLfloat)]

